#!/bin/sh
echo `date` "load ppp 3g-dns config"
cat /tmp/resolv.conf.ppp > /tmp/resolv.conf.auto

wan_proto=$(uci get network.wan.proto)
if [ "$wan_proto" == "pptp" ]; then
	/sbin/update_sys_dns
fi

/sbin/update_lan_dns
/etc/init.d/dnsmasq stop
/etc/init.d/dnsmasq start
