#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

. /etc/functions.sh

START=11

USE_PROCD=1

start_service() {

	if [ -f /etc/passwd+ ]; then
		rm /etc/passwd+
	fi

	#protect login root id
	chk_password=$(cat /etc/passwd | grep root:)
	[ -z "$chk_password" ] && {
		echo "root::0:0:root:/:/bin/ash" >> /etc/passwd
	}

	config_load system
	config_get password main pwd
	(echo "$password"; sleep 1; echo "$password") | passwd

	if [ -f /etc/passwd+ ]; then
		rm /etc/passwd+
	fi
}
