#!/bin/sh
. /lib/functions.sh

LOG_PATH="/var/run/luci-reload-status"

apply_config() {
	config_get init "$1" init
	config_get exec "$1" exec
	config_get test "$1" test

	echo "$2" >> $LOG_PATH

	[ -n "$init" ] && reload_init "$2" "$init" "$test"
	[ -n "$exec" ] && reload_exec "$2" "$exec" "$test"
}

reload_exec() {
	local service="$1"
	local ok="$3"
	set -- $2
	local cmd="$1"; shift
	
	[ -x "$cmd" ] && {
		echo "Reloading $service... " >> $LOG_PATH
		( $cmd "$@" ) 2>/dev/null 1>&2
		[ -n "$ok" -a "$?" != "$ok" ] && echo '!!! Failed to reload' $service '!!!' >> $LOG_PATH
	}
}

reload_init() {
	[ -x /etc/init.d/$2 ] && {
		echo "Reloading $1... " >> $LOG_PATH
		/etc/init.d/$2 reload >/dev/null 2>&1
		[ -n "$3" -a "$?" != "$3" ] && echo '!!! Failed to reload' $1 '!!!' >> $LOG_PATH
	}
}

lock "/var/run/luci-reload"

config_load ucitrack

for i in $*; do
	config_foreach apply_config $i $i
done

rm -f $LOG_PATH
lock -u "/var/run/luci-reload"
